version: "3.8"

services:

  ohmyfood:
    container_name: ohmyfood
    build:
        context: .
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    command: ["node", "server.js"]
      
volumes:
  database: